#### Packages ####
library(GenomicFeatures)

txdb <- makeTxDbFromEnsembl(organism="Homo sapiens",
                            release=89,
                            circ_seqs=NULL,
                            server="ensembldb.ensembl.org",
                            username="anonymous", password=NULL, port=0L,
                            tx_attrib=NULL)

excludedChrom <- c("CHR_HG107_PATCH",
                   "CHR_HG109_PATCH",
                   "CHR_HG126_PATCH",
                   "CHR_HG1277_PATCH",
                   "CHR_HG1296_PATCH",
                   "CHR_HG1298_PATCH",
                   "CHR_HG1299_PATCH",
                   "CHR_HG1309_PATCH",
                   "CHR_HG1311_PATCH",
                   "CHR_HG1320_PATCH",
                   "CHR_HG1342_HG2282_PATCH",
                   "CHR_HG1362_PATCH",
                   "CHR_HG1384_PATCH",
                   "CHR_HG1395_PATCH",
                   "CHR_HG1398_PATCH",
                   "CHR_HG142_HG150_NOVEL_TEST",
                   "CHR_HG1445_PATCH",
                   "CHR_HG1466_PATCH",
                   "CHR_HG1485_PATCH",
                   "CHR_HG1506_PATCH",
                   "CHR_HG1507_PATCH",
                   "CHR_HG1509_PATCH",
                   "CHR_HG151_NOVEL_TEST",
                   "CHR_HG1521_PATCH",
                   "CHR_HG1523_PATCH",
                   "CHR_HG1524_PATCH",
                   "CHR_HG1531_PATCH",
                   "CHR_HG1535_PATCH",
                   "CHR_HG1651_PATCH",
                   "CHR_HG1708_PATCH",
                   "CHR_HG1815_PATCH",
                   "CHR_HG1817_1_PATCH",
                   "CHR_HG1832_PATCH",
                   "CHR_HG1_PATCH",
                   "CHR_HG2002_PATCH",
                   "CHR_HG2021_PATCH",
                   "CHR_HG2022_PATCH",
                   "CHR_HG2023_PATCH",
                   "CHR_HG2030_PATCH",
                   "CHR_HG2046_PATCH",
                   "CHR_HG2047_PATCH", 
                   "CHR_HG2057_PATCH",
                   "CHR_HG2058_PATCH",
                   "CHR_HG2060_PATCH",
                   "CHR_HG2062_PATCH",
                   "CHR_HG2063_PATCH",
                   "CHR_HG2066_PATCH",
                   "CHR_HG2067_PATCH",
                   "CHR_HG2068_PATCH",
                   "CHR_HG2072_PATCH",
                   "CHR_HG2087_PATCH")

seqlevels(txdb) <- seqlevels(txdb)[!(seqlevels(txdb) %in% excludedChrom)]

