workdir: "/rds/project/rs2099/rds-rs2099-toxgenomics/sita/" + config['dir']
localrules: all, run_eisa

rule all:
    input:
        "processed/MAplot.png",
        "processed/DEstats.txt"

rule quasr_map_count:
    input:
        sample_file = "SampleFile.txt",
        metadata = "SraRunTable.txt"
    output:
        exon = "processed/ExonicCounts.txt",
        intron = "processed/IntronicCounts.txt"
    threads: 16
    run:
        shell("python3 /home/xwy21/project/sita/script/generate_samplefile.py -m {input.metadata} -e fastq")
        shell("Rscript /home/xwy21/project/sita/script/02_alignment_and_counting.R -i {input.sample_file} -m {input.metadata}")

rule run_eisa:
    input:
        exon = "processed/ExonicCounts.txt",
        intron = "processed/IntronicCounts.txt"
    output:
        "processed/MAplot.png",
        "processed/DEstats.txt"
    run:
        shell("Rscript /home/xwy21/project/sita/script/03_eisa.R -i {input.intron} -e {input.exon}")

