workdir: "/rds/project/rs2099/rds-rs2099-toxgenomics/sita/thap_hek"

rule all:
    input:
        "processed/MAplot.png",
        "processed/DEstats.txt"

rule quasr_map_count:
    input:
        "SampleFile.txt"
    output:
        exon = "processed/ExonicCounts.txt",
        intron = "processed/IntronicCounts.txt"
    shell:
        "mkdir bam"
    script:
        """
        /home/xwy21/project/sita/script/02_alignment_and_counting.R -i {input}
        """

rule run_eisa:
    input:
        exon = "processed/ExonicCounts.txt",
        intron = "processed/IntronicCounts.txt"
    output:
        "processed/MAplot.png",
        "processed/DEstats.txt"
    script:
        """
        /home/xwy21/project/sita/script/03_eisa.R -i {input.intron} -e {input.exon}
        """

